### ISSUE TITLE
Spaces inside "TB floating-point port" file (for T_ZFR0 and ,Y)

### ISSUE THREAD

**Issue by BartGo** [marktmiller/atari-8-bit-forth-projects#1]
I have tried to import your library and observed multiple issues with additional spaces inside "TB floating-point port" file:
* inside "T_ ZFR0" in line 23 (likely, should become T_ ZFR0)
* inside ", Y" in lines 245, 266, 287, 308, 329 (likely, should become ",Y"

For a lack of a better method, I am importing the code on PC through Altirra's "Paste" functionality. I use "0 WARNING !" before the import and depress CAPS LOCK so that lowecaser characters are correctly pasted. I have an alternative half-manual method (transformation to screens) but it may introduce additional problems.

I do not submit the code change directly as I am not yet able to perform any deeper checks (also, my assembly knowledge is minimal) but I hope that even such simple checks help a little.

**Comment by marktmiller** [comment]
Thanks for letting me know about these errors.

What I've posted here is basically a "transcribed" copy of the code I used in Forth. I haven't been able to export the code directly to text. So, this is the best I can do. I'll fix these errors.

The ", Y" problem looks to be from some copying/pasting I did, since the code was pretty repetitive. The error got in the first instance, and I just copied it a bunch of times.

The reason for this is the MADS assembler source uses macros for these situations, and I had to manually expand them, because I didn't know how to replicate the macro action in Forth code.

**Comment by marktmiller** [comment]
Just to "head you off at the pass," I found another typo in my code. It's in the definition for F_1DEG at line 1564. It appears as "FPAC". It should be "FP". I have fixed it, but just letting you know, in case you run into it.

"FPAC" was an old word I was using while developing this library. It no longer applies.

Also, I've moved a few definitions from the "Turbo Basic supplement" file to the bottom of "TB floating-point port," since I realized they're not needed for the Turbo Basic port to work, but they are "nice to have's."

These are: FVAR, FCONST, and FARRAY. If you've already loaded the "supplement" (assume you have), you already have these definitions, and do not need to run them through again.
