### ISSUE TITLE
NOT from "TB floating-point port" not recognized 

### ISSUE THREAD

**Issue by BartGo** [marktmiller/atari-8-bit-forth-projects#2]
While importing the  "TB floating-point port" file the definition of F<> (line 1005) complains about "NOT" being unknown.

"NOT" actually exists in the APX Forth - but it sits inside the ASSEMBLY vocabulary

Perhaps 0= or its equivalent suitable for FP should be used instead?

**Comment by marktmiller** [comment]
This is a definition I forgot to include in the "Turbo Basic supplement" file. I've fixed that. Yes, the definition is simply:

: NOT 0 = ;

I've been cautious about using "0=" (without a space) in my Forth code, because I've seen it conflict with a "0=" word that exists in the ASSEMBLY vocabulary, screwing up my Forth code. They are _not_ the same thing. I'm not really sure how the NOT logic works in the assembler. I just know that it does. :)

As I got finished with this port, I discovered there's a FORTH vocabulary that I should probably invoke more often when using the assembler, since it "shuts off" any other vocabulary that may be active, and returns you to the global Forth vocabulary.
